### ISSUE TITLE
Padding causes parsing errors

### ISSUE THREAD

**Issue by SiFall** [ugswork/eaudit#5]
Hi,
when using the padding parameter for ecapd (e..g, `./ecapd -p 4 -c sc.data`),  eaudit (e.g., `./eaudit -I sc.data`) has problems with parsing the records:

```
[...]
***** Error while parsing a record: at offset 884076:

**** Text following error is: 
K�e{�;p��5�5
k�e@
 *******************************************
***** Missing newline: at offset 884154:
k�e@��
**** Text following error is: 
o�eD�<`�/proc/142
 *******************************************
[...]
eParser: Terminating after reading 1431388 bytes.
[...]
```

I also tried different values for padding (as far as I understand <256 bytes are supported), different systems/kernels (5.10, 6.1 and 6.8), different llvm/clang versions (14 and 16) and bcc versions (master, 0.30, 0.27), but the issue seems to occur in all tested instances.
Hope you can shed some light on how to use the padding parameter. Thank you!

**Comment by profsekar** [comment]
Why are you using padding? It is only meant for performance experiments.
The resulting data cannot be parsed.

**Comment by SiFall** [comment]
I see, that explains the problem. Thanks!
